#!/usr/bin/env bash
#  Install nginx web server
#  Configures Nginx server so that /redirect_me
#+ is redirecting to another page.
#  Configures Nginx server to have a custom 404
#+ page that contains the string Ceci n'est pas une page.
#  Configures Nginx so that its HTTP response contains a custom header.

sudo apt-get -y update
sudo apt-get -y install nginx
ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/ a rewrite ^/redirect_me https://www.google.com permanent;' /etc/nginx/sites-available/default
sudo touch /usr/share/nginx/html/custom_404.html
sudo echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sudo sed -i '/server_name _;/a error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
sudo service nginx restart