#!/usr/bin/env bash
#  displays the content of the file /etc/passwd
#+ only displays name, group id and shell full path for user

while IFS= read -r LINE; do
    echo "$LINE" | cut -d':' -f1,4,7
done < /etc/passwd